/**
 * This file is autogenerated.
 * Please do not touch it manually.
 * If you wish to update the versions of the library,
 * update the version in the `CMakeLists.txt` file, and reload the CMake project.
 */

#ifndef LILITH_VERSION_H
#define LILITH_VERSION_H

#define LILITH_MAJOR_VERSION 0
#define LILITH_MINOR_VERSION 1
#define LILITH_PATCH_VERSION 0
#define LILITH_VERSION_SUFFIX "alpha"
#define LILITH_VERSION "0.1.0-alpha"

#include <cstdint>
#include <string>

namespace lilith
{
class Version
{
public:
    static std::uint32_t getMajorVersion() { return LILITH_MAJOR_VERSION; }

    static std::uint32_t getMinorVersion() { return LILITH_MINOR_VERSION; }

    static std::uint32_t getPatchVersion() { return LILITH_PATCH_VERSION; }

    static std::string getVersionSuffix() { return LILITH_VERSION_SUFFIX; }

    static std::string getVersion() { return LILITH_VERSION; }
};
}    // namespace lilith

#endif    // LILITH_VERSION_H
