name: CMake

on:
  push:
    branches: [ "main", "development**", "release/**" ]
  pull_request:
    branches: [ "main", "development**", "release/**" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    #    strategy:
    #      matrix:
    #        os: [ macos-latest, ubuntu-latest ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j ${nproc}

      - name: Run Parsing Examples
        working-directory: ${{github.workspace}}/build
        run: ${{github.workspace}}/build/bin/LilithExamples_ParsingExample

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ${{github.workspace}}/build/bin/LilithTests
