/**
 * This file is autogenerated.
 * Please do not touch it manually.
 * If you wish to update the versions of the library,
 * update the version in the `CMakeLists.txt` file, and reload the CMake project.
 */

#ifndef DESCENDANTS_VERSION_H
#define DESCENDANTS_VERSION_H

#define DESCENDANTS_MAJOR_VERSION 0
#define DESCENDANTS_MINOR_VERSION 1
#define DESCENDANTS_PATCH_VERSION 0
#define DESCENDANTS_VERSION_SUFFIX "alpha"
#define DESCENDANTS_VERSION "0.1.0-alpha"

#include <cstdint>
#include <string>

namespace descendants
{
class Version
{
public:
    static std::uint32_t getMajorVersion() { return DESCENDANTS_MAJOR_VERSION; }

    static std::uint32_t getMinorVersion() { return DESCENDANTS_MINOR_VERSION; }

    static std::uint32_t getPatchVersion() { return DESCENDANTS_PATCH_VERSION; }

    static std::string getVersionSuffix() { return DESCENDANTS_VERSION_SUFFIX; }

    static std::string getVersion() { return DESCENDANTS_VERSION; }
};
}    // namespace descendants

#endif    // DESCENDANTS_VERSION_H
